### ISSUE TITLE
Build 1.0 alpha 28 Functionality

### ISSUE THREAD

**Issue by bullsear** [scoin/multichain-node#10]
This a great module.  Thanks a million.  Any chance we can get the newer build's functionality?  I'm running build 1.0 alpha 28 and I really need createRawSendFrom(). 

http://www.multichain.com/developers/json-rpc-api/

Thanks in advance.

**Comment by scoin** [comment]
Thanks @bullsear, yes those are coming and apologies for not being as timely as I've been in the past.

Pull requests welcome.

**Comment by scoin** [comment]
5a2d1e9b2308eed5733ece2ab20130f0e1dc3036
