### ISSUE TITLE
error on test multichain 1.0 bet a2 protocol 100008

### ISSUE THREAD

**Issue by vanessasmith** [scoin/multichain-node#17]
error when running npm test

in test: list stream keys 

code: -8  
message: invalid parameter value type, should be boolean.
unhandled rejection     no stack trace

**Comment by ganadara135** [comment]
can you write the function name as a whole?
It would be a parameter problem.
Compare the function name's parameter with my multichain-node in github.

**Comment by scoin** [comment]
fixed in bf16a90 
thanks!
