### ISSUE TITLE
Adding API methods from Multichain Version 1.0 beta 2

### ISSUE THREAD

**Issue by amolpednekar** [scoin/multichain-node#18]
In Multichain Version 1.0 beta 2, they added 3 API methods:

liststreamblockitems,
listblocks,
appendrawtransaction,

which are currently unavailable in this wrapper as it has not been updated after 1.0-beta-1. 

I can add them and submit a pull request if they are currently not being worked on by you guys.

**Comment by scoin** [comment]
All methods from 1.0.2 are now available. In the future, please feel free to submit a PR.
