### ISSUE TITLE
getAddressBalancePromise not working in Node.js

### ISSUE THREAD

**Issue by samantaraysambitdash** [scoin/multichain-node#20]
Hi,

I have my part of code as well. PFB.

function getAddressBalance(address)
{
   console.log(JSON.stringify(address.address));
    //var addr = address.address;
   //var minconf = {minconf: 1};
   var addr = [address.address];
    console.log(addr);
    
   multichain.getAddressBalances(addr,(err, res) => {
       
        console.log(err);
	         return res;
	})
   
}   

Please check on the issue.

**Comment by scoin** [comment]
The first argument to an RPC function is always the parameters object to be parsed by this library, or an array which will go unparsed.
