### ISSUE TITLE
Having issues connecting to multichain using multichain-node

### ISSUE THREAD

**Issue by hai-pdx** [scoin/multichain-node#21]
I've been scratching my head on this for a few days.  Hopefully someone can help.

I installed multichain-node in my project using:
`npm install multichain-node -save`

In my .js code, I'm trying to test the connection.  I have:
```

let multichain = require("multichain-node")({
    port: 2780,
    host: '192.168.110.76',
    user: "multichainrpc",
    pass: "xxxx"
});

multichain.getInfo((err, info) => {
    if(err){
        throw err;
    }
    console.log(info);
})
```

When I load up the page in my browsers, I'm unable to connect.  I get the following error:

![screen shot 2017-11-02 at 4 31 37 pm](https://user-images.githubusercontent.com/573116/32355338-567bdeba-bfeb-11e7-9403-b54fca6f57a4.png)

I triple checked the rpc-port and credentials and they are set correctly.  I'm also able connect running curl from the command line.

Any help is much appreciated.  Thank you!

**Comment by scoin** [comment]
Looks like a CORS issue between the multichain server and the React preflight request. You probably want to set up a proxy.
