### ISSUE TITLE
Unable to call listAssetTransactions

### ISSUE THREAD

**Issue by maleficarum** [scoin/multichain-node#22]
I'm calling the method listAssetTransactions as follows 

``javascript
multichain.listAssetTransactions({"asset":"MyAsset"}, (error, transactions) => {
console.log(transactions);
});
``

And I got the next error 

`
{ code: -703, message: 'Not subscribed to this asset' }
`

I assume that I have to subscribe to 'MyAsset', but there is no method in the API to do that. am I missing some step ?

**Comment by scoin** [comment]
There is a subscribe method. Provide it with params `{stream: "MyAsset"}`
