### ISSUE TITLE
createrawtransaction function is not working properly

### ISSUE THREAD

**Issue by utkarshv** [scoin/multichain-node#28]
while using createrawtransaction function i got an error
 node_modules/multichain-node/lib/rpccall.js:40
                cb(err, res);
                ^

TypeError: cb is not a function

**Comment by scoin** [comment]
It appears you were not passing a callback function.

As of fc3d0af144081880dd560eb84945e7096b64e795 methods return a Promise. This may fix your issue.

If you are still experiencing this issue please reopen with a code snippet to reproduce.
