### ISSUE TITLE
Not all parameters exposed in signrawtransaction

### ISSUE THREAD

**Issue by davidiluvatar** [scoin/multichain-node#5]
Hello!
Not really sure why you would have intentionally left it out, but I can see that while multichain-cli implements:

`signrawtransaction tx-hex ( [{"txid":"id","vout":n,"scriptPubKey":"hex","redeemScript":"hex"},...] ["privatekey1",...] sighashtype )`

multichain-node/lib/commands.js only the first parameter:

`signRawTransaction: ["hexstring"]`

I have had to change commands.js in this way:

`signRawTransaction: ["hexstring", "scripts", "privatekeys"]`

Now I can sign raw transactions with private keys not in the wallet.

**Comment by scoin** [comment]
whoops, must have overlooked this. Want to submit PR?

**Comment by scoin** [comment]
aa878fe0d14c3dca838d934992690bd736ad08b2
